import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {ethers} from 'ethers';
import abi from '../constants/abi.json';
import {useEffect, useState} from 'react';

const contractAddress = '0xAb29B4eA2265458593C47B13C45a62012a3922DC';

function getEth() {
    const eth = window.ethereum;
    if (!eth) {
        console.log('Ethereum not enabled!');
    }
    return eth;
}

const hasAccounts = async () => {
    const eth = getEth();
    const accounts = await eth.request({method: 'eth_accounts'});

    return accounts && accounts.length;
}

const requestAccounts = async () => {
    const eth = getEth();
    const accounts = await eth.request({method: 'eth_requestAccounts'});

    return accounts && accounts.length;
}


export default function Home() {

    const [text, setText] = useState(0);
    const [counter, setCounter] = useState();


    const run = async () => {
        if (!await hasAccounts() && !await requestAccounts()) {
            console.log('Please let me take your money');
        }

        const provider = await new ethers.providers.Web3Provider(getEth());
        const signer = provider.getSigner();
        //console.log("Provider", provider.getNetwork().chainId.getNetwork().name)

        const counter = new ethers.Contract(
            contractAddress,
            abi,
            signer
        )

        setCounter(counter);

        const bigNum = await counter.getCount();
        setText(Number(bigNum));
    }

    const increment = async () => {
        try {
            await counter.count();
        } catch (e) {
            console.log(e.message)
        }
    }

    const listen = () => {

    }

    useEffect(() => {
        run().then();
    }, [])

    useEffect(() => {
        console.log(counter);
        counter?.on(counter?.filters?.CounterInc(), function (count) {
            console.log("Received counter data...")
            setText(Number(count));
        })
    }, [counter])


    return (
        <div className={styles.container}>
            <Head>
                <title>Hardhat</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Hardhat</a>
                </h1>
                <p>Smart Contract Text: {text}</p>
                <button onClick={() => increment()}>Count</button>
            </main>
        </div>
    )
}
